--
-- PostgreSQL database dump
--

\restrict BhoksptKVW2II8RdxRaaLubchnkH5jvehE9RxzOI1jkPnRL10bM9fxGS1dePhWd

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.0 (Debian 18.0-1.pgdg12+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activation_licenses; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.activation_licenses (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) DEFAULT NULL::character varying,
    license_number character varying(255) NOT NULL,
    used timestamp without time zone,
    user_id uuid,
    created timestamp without time zone NOT NULL,
    modified timestamp without time zone NOT NULL,
    device_id uuid,
    instance_id uuid,
    deleted_at timestamp without time zone
);


ALTER TABLE public.activation_licenses OWNER TO db;

--
-- Name: activation_licenses_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.activation_licenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activation_licenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_remote_config; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.app_remote_config (
    id bigint NOT NULL,
    version_id bigint,
    show_upgrade_button boolean DEFAULT false,
    created timestamp without time zone,
    modified timestamp without time zone,
    instance_id uuid,
    config_data text
);


ALTER TABLE public.app_remote_config OWNER TO db;

--
-- Name: app_remote_config_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.app_remote_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_remote_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cake_migrations; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.cake_migrations (
    id integer NOT NULL,
    version bigint NOT NULL,
    migration_name character varying(100) DEFAULT NULL::character varying,
    plugin character varying(100) DEFAULT NULL::character varying,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    breakpoint boolean DEFAULT false NOT NULL
);


ALTER TABLE public.cake_migrations OWNER TO db;

--
-- Name: cake_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.cake_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cake_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devices; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.devices (
    id uuid NOT NULL,
    device_uuid character varying(255) NOT NULL,
    custom_name character varying(255) DEFAULT NULL::character varying,
    hardware_model character varying(255) DEFAULT NULL::character varying,
    first_activation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_id uuid,
    created timestamp without time zone,
    modified timestamp without time zone,
    platform character varying(255) DEFAULT NULL::character varying,
    os_version character varying(255) DEFAULT NULL::character varying,
    app_version character varying(255) DEFAULT NULL::character varying,
    instance_id uuid,
    deleted_at timestamp without time zone
);


ALTER TABLE public.devices OWNER TO db;

--
-- Name: instances; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.instances (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    club_admin_id uuid,
    is_active boolean DEFAULT true NOT NULL,
    created timestamp without time zone,
    modified timestamp without time zone,
    deleted_at timestamp without time zone
);


ALTER TABLE public.instances OWNER TO db;

--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.password_resets (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false NOT NULL,
    created timestamp without time zone NOT NULL,
    modified timestamp without time zone NOT NULL
);


ALTER TABLE public.password_resets OWNER TO db;

--
-- Name: subscription_devices; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.subscription_devices (
    id bigint NOT NULL,
    subscription_id uuid NOT NULL,
    device_id uuid NOT NULL,
    created timestamp without time zone,
    modified timestamp without time zone
);


ALTER TABLE public.subscription_devices OWNER TO db;

--
-- Name: subscription_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.subscription_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.subscriptions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    stripe_subscription_id character varying(255) DEFAULT NULL::character varying,
    plan character varying(20) DEFAULT 'free'::character varying,
    status character varying(20) DEFAULT 'active'::character varying,
    max_devices_allowed integer DEFAULT 2,
    created timestamp without time zone,
    modified timestamp without time zone,
    deleted_at timestamp without time zone,
    current_period_start timestamp without time zone,
    current_period_end timestamp without time zone,
    cancel_at_period_end boolean DEFAULT false NOT NULL
);


ALTER TABLE public.subscriptions OWNER TO db;

--
-- Name: upgrade_tokens; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.upgrade_tokens (
    id uuid NOT NULL,
    token_string character varying(36) NOT NULL,
    device_uuid character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_used boolean DEFAULT false,
    created timestamp without time zone,
    modified timestamp without time zone,
    type character varying(20) DEFAULT 'upgrade'::character varying NOT NULL
);


ALTER TABLE public.upgrade_tokens OWNER TO db;

--
-- Name: users; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role text DEFAULT 'user'::text,
    stripe_customer_id text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    first_name character varying(100) DEFAULT NULL::character varying,
    last_name character varying(100) DEFAULT NULL::character varying,
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text, 'club_admin'::text])))
);


ALTER TABLE public.users OWNER TO db;

--
-- Name: versions; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.versions (
    id bigint NOT NULL,
    version character varying(255) NOT NULL,
    disabled boolean DEFAULT false,
    created timestamp without time zone,
    modified timestamp without time zone,
    instance_id uuid
);


ALTER TABLE public.versions OWNER TO db;

--
-- Name: versions_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activation_licenses; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.activation_licenses (id, email, name, license_number, used, user_id, created, modified, device_id, instance_id, deleted_at) FROM stdin;
1	ajibarra@gmail.com	Alejandro Ibarra	4AQA-O923-IDBA-CJ9H	2026-03-02 11:35:12.777393	\N	2026-02-27 17:45:14.821348	2026-03-02 11:35:12.777637	af9ebbf8-2907-4584-906e-7f320cc9ff25	1e74793a-d755-469a-b081-b1d5a516b407	\N
\.


--
-- Data for Name: app_remote_config; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.app_remote_config (id, version_id, show_upgrade_button, created, modified, instance_id, config_data) FROM stdin;
1	1	f	2026-02-25 11:23:58.51617	2026-02-25 13:32:40.282397	bfc6c923-3680-4967-8528-eb6d60bb09b7	{"app_name":"TriggerTime","full_app_name":"TriggerTime","home_url":"https:\\/\\/triggertime.es","package_name":"com.ibarracc.triggertime","version":"1.0.0-b6","build_number":"95a03c84","disabled_discipline_ids":[],"max_free_sessions":10,"iap_disabled":false,"enabled_iap_features":["shot_timer","export_sessions","unlimited_sessions","custom_disciplines"],"enabled_features":["shot_timer","export_sessions","unlimited_sessions","custom_disciplines"],"license":{"en":"TriggerTime is the exclusive property of its author. All intellectual property rights, including the source code, design, and commercial exploitation rights, are fully reserved by the developer. This application is distributed under a personal use license, and the author reserves the right to introduce future updates, premium modules, or services that may require in-app purchases, as well as the authority to distribute or license the software to third parties at their sole discretion.","es":"TriggerTime es propiedad exclusiva de su autor. Todos los derechos de propiedad intelectual, incluyendo el c\\u00f3digo fuente, dise\\u00f1o y derechos de explotaci\\u00f3n comercial, est\\u00e1n \\u00edntegramente reservados por el desarrollador. Esta aplicaci\\u00f3n se distribuye bajo una licencia de uso personal, reserv\\u00e1ndose el autor el derecho de incorporar en el futuro actualizaciones, m\\u00f3dulos o servicios premium que podr\\u00edan requerir compras dentro de la aplicaci\\u00f3n, as\\u00ed como la facultad de distribuir o licenciar el software a terceros seg\\u00fan su propio criterio.","ca":"TriggerTime \\u00e9s propietat exclusiva del seu autor. Tots els drets de propietat intel\\u00b7lectual, incloent-hi el codi font, el disseny i els drets d'explotaci\\u00f3 comercial, estan \\u00edntegrament reservats pel desenvolupador. Aquesta aplicaci\\u00f3 es distribueix sota una llic\\u00e8ncia d'\\u00fas personal, reservant-se l'autor el dret d'incorporar en el futur actualitzacions, m\\u00f2duls o serveis pr\\u00e8mium que podrien requerir compres dins de l'aplicaci\\u00f3, aix\\u00ed com la facultat de distribuir o llicenciar el programari a tercers segons el seu propi criteri.","gl":"TriggerTime \\u00e9 propiedade exclusiva do seu autor. Todos os dereitos de propiedade intelectual, inclu\\u00edndo o c\\u00f3digo fonte, dese\\u00f1o e dereitos de explotaci\\u00f3n comercial, est\\u00e1n integramente reservados polo desenvolvedor. Esta aplicaci\\u00f3n distrib\\u00faese baixo unha licencia de uso persoal, reserv\\u00e1ndose o autor o dereito de incorporar no futuro actualizaci\\u00f3ns, m\\u00f3dulos ou servizos premium que poder\\u00edan requirir compras dentro da aplicaci\\u00f3n, as\\u00ed como a facultade de distribu\\u00edr ou licenciar o software a terceiros segundo o seu propio criterio.","eu":"TriggerTime bere egilearen jabetza esklusiboa da. Jabetza intelektualaren eskubide guztiak, iturburu-kodea, diseinua eta merkataritza-ustiapenerako eskubideak barne, garatzaileak erreserbatu ditu osorik. Aplikazio hau erabilera pertsonalerako lizentziapean banatzen da; egileak beretzat gordetzen du etorkizunean aplikazio barruko erosketak eska ditzaketen eguneratzeak, moduluak edo premium zerbitzuak gehitzeko eskubidea, baita softwarea hirugarrenei banatzeko edo lizentziatzeko gaitasuna ere, bere irizpidearen arabera.","fr":"TriggerTime est la propri\\u00e9t\\u00e9 exclusive de son auteur. Tous les droits de propri\\u00e9t\\u00e9 intellectuelle, y compris le code source, le design et les droits d'exploitation commerciale, sont int\\u00e9gralement r\\u00e9serv\\u00e9s par le d\\u00e9veloppeur. Cette application est distribu\\u00e9e sous une licence d'utilisation personnelle, l'auteur se r\\u00e9servant le droit d'introduire \\u00e0 l'avenir des mises \\u00e0 jour, des modules ou des services premium pouvant n\\u00e9cessiter des achats int\\u00e9gr\\u00e9s, ainsi que la facult\\u00e9 de distribuer ou de conc\\u00e9der des licences du logiciel \\u00e0 des tiers \\u00e0 sa seule discr\\u00e9tion.","de":"TriggerTime ist das ausschlie\\u00dfliche Eigentum seines Autors. Alle geistigen Eigentumsrechte, einschlie\\u00dflich des Quellcodes, des Designs und der kommerziellen Verwertungsrechte, sind dem Entwickler vorbehalten. Diese Anwendung wird unter einer Lizenz f\\u00fcr den pers\\u00f6nlichen Gebrauch vertrieben, wobei sich der Autor das Recht vorbeh\\u00e4lt, k\\u00fcnftig Updates, Premium-Module oder Dienste einzuf\\u00fchren, die In-App-K\\u00e4ufe erfordern k\\u00f6nnen, sowie die Befugnis, die Software nach eigenem Ermessen an Dritte zu vertreiben oder zu lizenzieren.","pt":"TriggerTime \\u00e9 propriedade exclusiva do seu autor. Todos os direitos de propriedade intelectual, incluindo o c\\u00f3digo-fonte, design e direitos de explora\\u00e7\\u00e3o comercial, est\\u00e3o integralmente reservados pelo desenvolvedor. Esta aplica\\u00e7\\u00e3o \\u00e9 distribu\\u00edda sob uma licen\\u00e7a de uso pessoal, reservando-se o autor o direito de introduzir no futuro atualiza\\u00e7\\u00f5es, m\\u00f3dulos ou servi\\u00e7os premium que possam exigir compras na aplica\\u00e7\\u00e3o, bem como a autoridade para distribuir ou licenciar o software a terceiros conforme o seu pr\\u00f3prio crit\\u00e9rio."},"session_types":[{"id":"training","labels":{"en":"Training","es":"Entrenamiento","ca":"Entrenament","gl":"Adestramento","eu":"Entrenamendua","fr":"Entra\\u00eenement","de":"Training","pt":"Treino"},"is_training":true,"color_hex":"#A8A8A8"},{"id":"social","labels":{"en":"Social Match","es":"Social","ca":"Social","gl":"Social","eu":"Soziala","fr":"Match de club","de":"Vereinsmeisterschaft","pt":"Prova de clube"},"is_training":false,"color_hex":"#E0E0E0"},{"id":"socialAutonomico","labels":{"en":"Regional Social Match","es":"Social Auton\\u00f3mico","ca":"Social Auton\\u00f2mic","gl":"Social Auton\\u00f3mico","eu":"Sozial Autonomikoa","fr":"Match r\\u00e9gional","de":"Regionalsportfest","pt":"Prova regional"},"is_training":false,"color_hex":"#92D050"},{"id":"provincialChampionship","labels":{"en":"Provincial Championship","es":"Cto. Provincial","ca":"Campionat Provincial","gl":"Campionato Provincial","eu":"Probintziako Txapelketa","fr":"Championnat provincial","de":"Provinzmeisterschaft","pt":"Campeonato provincial"},"is_training":false,"color_hex":"#96B3D7"},{"id":"regionalChampionship","labels":{"en":"Regional Championship","es":"Campeonato Regional","ca":"Campionat Regional","gl":"Campionato Regional","eu":"Eskualdeko Txapelketa","fr":"Championnat r\\u00e9gional","de":"Regionalmeisterschaft","pt":"Campeonato Regional"},"is_training":false,"color_hex":"#963533"},{"id":"nationalChampionship","labels":{"en":"National Championship","es":"Campeonato Nacional","ca":"Campionat Nacional","gl":"Campionato Nacional","eu":"Txapelketa Nazionala","fr":"Championnat national","de":"Nationale Meisterschaft","pt":"Campeonato nacional"},"is_training":false,"color_hex":"#FFC001"}],"icon_android_path":"assets\\/triggertime_android_new.png","icon_ios_path":"assets\\/triggertime_ios_new.png","home_icon_path":"assets\\/triggertime_home_logo.png","home_icon_dark_path":"assets\\/triggertime_home_logo_dark.png","activation_required":false,"supabase_url":"","supabase_anon_key":""}
3	\N	f	2026-02-26 09:29:28.503417	2026-02-27 20:23:13.272946	1e74793a-d755-469a-b081-b1d5a516b407	{"app_name":"TriggerTime","full_app_name":"TriggerTime","home_url":"https:\\/\\/triggertime.es","app_url":"https:\\/\\/triggertime.ddev.site","package_name":"com.ibarracc.triggertime","version":"1.0.0-b6","build_number":"95a03c84","disabled_discipline_ids":[],"max_free_sessions":10,"iap_disabled":false,"enabled_features":["export_sessions","unlimited_sessions"],"license":{"en":"TriggerTime is the exclusive property of its author. All intellectual property rights, including the source code, design, and commercial exploitation rights, are fully reserved by the developer. This application is distributed under a personal use license, and the author reserves the right to introduce future updates, premium modules, or services that may require in-app purchases, as well as the authority to distribute or license the software to third parties at their sole discretion.","es":"TriggerTime es propiedad exclusiva de su autor. Todos los derechos de propiedad intelectual, incluyendo el c\\u00f3digo fuente, dise\\u00f1o y derechos de explotaci\\u00f3n comercial, est\\u00e1n \\u00edntegramente reservados por el desarrollador. Esta aplicaci\\u00f3n se distribuye bajo una licencia de uso personal, reserv\\u00e1ndose el autor el derecho de incorporar en el futuro actualizaciones, m\\u00f3dulos o servicios premium que podr\\u00edan requerir compras dentro de la aplicaci\\u00f3n, as\\u00ed como la facultad de distribuir o licenciar el software a terceros seg\\u00fan su propio criterio.","ca":"TriggerTime \\u00e9s propietat exclusiva del seu autor. Tots els drets de propietat intel\\u00b7lectual, incloent-hi el codi font, el disseny i els drets d'explotaci\\u00f3 comercial, estan \\u00edntegrament reservats pel desenvolupador. Aquesta aplicaci\\u00f3 es distribueix sota una llic\\u00e8ncia d'\\u00fas personal, reservant-se l'autor el dret d'incorporar en el futur actualitzacions, m\\u00f2duls o serveis pr\\u00e8mium que podrien requerir compres dins de l'aplicaci\\u00f3, aix\\u00ed com la facultat de distribuir o llicenciar el programari a tercers segons el seu propi criteri.","gl":"TriggerTime \\u00e9 propiedade exclusiva do seu autor. Todos os dereitos de propiedade intelectual, inclu\\u00edndo o c\\u00f3digo fonte, dese\\u00f1o e dereitos de explotaci\\u00f3n comercial, est\\u00e1n integramente reservados polo desenvolvedor. Esta aplicaci\\u00f3n distrib\\u00faese baixo unha licencia de uso persoal, reserv\\u00e1ndose o autor o dereito de incorporar no futuro actualizaci\\u00f3ns, m\\u00f3dulos ou servizos premium que poder\\u00edan requirir compras dentro da aplicaci\\u00f3n, as\\u00ed como a facultade de distribu\\u00edr ou licenciar o software a terceiros segundo o seu propio criterio.","eu":"TriggerTime bere egilearen jabetza esklusiboa da. Jabetza intelektualaren eskubide guztiak, iturburu-kodea, diseinua eta merkataritza-ustiapenerako eskubideak barne, garatzaileak erreserbatu ditu osorik. Aplikazio hau erabilera pertsonalerako lizentziapean banatzen da; egileak beretzat gordetzen du etorkizunean aplikazio barruko erosketak eska ditzaketen eguneratzeak, moduluak edo premium zerbitzuak gehitzeko eskubidea, baita softwarea hirugarrenei banatzeko edo lizentziatzeko gaitasuna ere, bere irizpidearen arabera.","fr":"TriggerTime est la propri\\u00e9t\\u00e9 exclusive de son auteur. Tous les droits de propri\\u00e9t\\u00e9 intellectuelle, y compris le code source, le design et les droits d'exploitation commerciale, sont int\\u00e9gralement r\\u00e9serv\\u00e9s par le d\\u00e9veloppeur. Cette application est distribu\\u00e9e sous une licence d'utilisation personnelle, l'auteur se r\\u00e9servant le droit d'introduire \\u00e0 l'avenir des mises \\u00e0 jour, des modules ou des services premium pouvant n\\u00e9cessiter des achats int\\u00e9gr\\u00e9s, ainsi que la facult\\u00e9 de distribuer ou de conc\\u00e9der des licences du logiciel \\u00e0 des tiers \\u00e0 sa seule discr\\u00e9tion.","de":"TriggerTime ist das ausschlie\\u00dfliche Eigentum seines Autors. Alle geistigen Eigentumsrechte, einschlie\\u00dflich des Quellcodes, des Designs und der kommerziellen Verwertungsrechte, sind dem Entwickler vorbehalten. Diese Anwendung wird unter einer Lizenz f\\u00fcr den pers\\u00f6nlichen Gebrauch vertrieben, wobei sich der Autor das Recht vorbeh\\u00e4lt, k\\u00fcnftig Updates, Premium-Module oder Dienste einzuf\\u00fchren, die In-App-K\\u00e4ufe erfordern k\\u00f6nnen, sowie die Befugnis, die Software nach eigenem Ermessen an Dritte zu vertreiben oder zu lizenzieren.","pt":"TriggerTime \\u00e9 propriedade exclusiva do seu autor. Todos os direitos de propriedade intelectual, incluindo o c\\u00f3digo-fonte, design e direitos de explora\\u00e7\\u00e3o comercial, est\\u00e3o integralmente reservados pelo desenvolvedor. Esta aplica\\u00e7\\u00e3o \\u00e9 distribu\\u00edda sob uma licen\\u00e7a de uso pessoal, reservando-se o autor o direito de introduzir no futuro atualiza\\u00e7\\u00f5es, m\\u00f3dulos ou servi\\u00e7os premium que possam exigir compras na aplica\\u00e7\\u00e3o, bem como a autoridade para distribuir ou licenciar o software a terceiros conforme o seu pr\\u00f3prio crit\\u00e9rio."},"session_types":[{"id":"training","labels":{"en":"Training","es":"Entrenamiento","ca":"Entrenament","gl":"Adestramento","eu":"Entrenamendua","fr":"Entra\\u00eenement","de":"Training","pt":"Treino"},"is_training":true,"color_hex":"#A8A8A8"},{"id":"social","labels":{"en":"Social Match","es":"Social","ca":"Social","gl":"Social","eu":"Soziala","fr":"Match de club","de":"Vereinsmeisterschaft","pt":"Prova de clube"},"is_training":false,"color_hex":"#E0E0E0"},{"id":"socialAutonomico","labels":{"en":"Regional Social Match","es":"Social Auton\\u00f3mico","ca":"Social Auton\\u00f2mic","gl":"Social Auton\\u00f3mico","eu":"Sozial Autonomikoa","fr":"Match r\\u00e9gional","de":"Regionalsportfest","pt":"Prova regional"},"is_training":false,"color_hex":"#92D050"},{"id":"provincialChampionship","labels":{"en":"Provincial Championship","es":"Cto. Provincial","ca":"Campionat Provincial","gl":"Campionato Provincial","eu":"Probintziako Txapelketa","fr":"Championnat provincial","de":"Provinzmeisterschaft","pt":"Campeonato provincial"},"is_training":false,"color_hex":"#96B3D7"},{"id":"regionalChampionship","labels":{"en":"Regional Championship","es":"Campeonato Regional","ca":"Campionat Regional","gl":"Campionato Regional","eu":"Eskualdeko Txapelketa","fr":"Championnat r\\u00e9gional","de":"Regionalmeisterschaft","pt":"Campeonato Regional"},"is_training":false,"color_hex":"#963533"},{"id":"nationalChampionship","labels":{"en":"National Championship","es":"Campeonato Nacional","ca":"Campionat Nacional","gl":"Campionato Nacional","eu":"Txapelketa Nazionala","fr":"Championnat national","de":"Nationale Meisterschaft","pt":"Campeonato nacional"},"is_training":false,"color_hex":"#FFC001"}],"icon_android_path":"assets\\/triggertime_android_new.png","icon_ios_path":"assets\\/triggertime_ios_new.png","home_icon_path":"assets\\/triggertime_home_logo.png","home_icon_dark_path":"assets\\/triggertime_home_logo_dark.png","activation_required":true,"show_upgrade_button":true,"test":true}
\.


--
-- Data for Name: cake_migrations; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.cake_migrations (id, version, migration_name, plugin, start_time, end_time, breakpoint) FROM stdin;
1	20260221165546	CreateUsers	\N	2026-02-23 10:38:31	2026-02-23 10:38:31	f
2	20260221165547	CreateActivationLicenses	\N	2026-02-23 11:15:42	2026-02-23 11:15:42	f
3	20260221165548	CreateSubscriptions	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
4	20260221165549	CreateDevices	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
5	20260221165550	CreateSubscriptionDevices	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
6	20260221165551	CreateUpgradeTokens	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
7	20260221165552	CreateVersions	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
8	20260221165553	CreateAppRemoteConfig	\N	2026-02-23 11:20:12	2026-02-23 11:20:12	f
9	20260224145008	AddFieldsToDevices	\N	2026-02-24 14:51:59	2026-02-24 14:51:59	f
10	20260224145358	AlterUpgradeTokens	\N	2026-02-24 14:55:01	2026-02-24 14:55:01	f
11	20260224145751	AlterActivationLicenses	\N	2026-02-24 14:58:12	2026-02-24 14:58:12	f
12	20260225043517	CreateInstances	\N	2026-02-25 04:36:27	2026-02-25 04:36:27	f
13	20260225043518	RefactorAppInstances	\N	2026-02-25 04:37:05	2026-02-25 04:37:05	f
14	20260225043519	SeedDefaultAdmin	\N	2026-02-25 04:37:40	2026-02-25 04:37:40	f
15	20260225045011	AddSoftDeletes	\N	2026-02-25 04:50:25	2026-02-25 04:50:25	f
16	20260226000001	AddNamesToUsers	\N	2026-02-25 05:40:51	2026-02-25 05:40:51	f
17	20260226000002	AddDatesToSubscriptions	\N	2026-02-25 05:40:51	2026-02-25 05:40:51	f
18	20260226000003	CreatePasswordResets	\N	2026-02-25 05:40:51	2026-02-25 05:40:51	f
19	20260226000004	UpdateUsersRoleCheck	\N	2026-02-25 06:27:27	2026-02-25 06:27:27	f
20	20260225092837	AddConfigDataToAppRemoteConfig	\N	2026-02-25 09:29:41	2026-02-25 09:29:41	f
21	20260225105210	RemoveShowUpgradeButtonFromAppRemoteConfig	\N	2026-02-25 10:52:35	2026-02-25 10:52:35	f
22	20260225171300	AddCancelAtPeriodEndToSubscriptions	\N	2026-02-25 17:15:07	2026-02-25 17:15:07	f
23	20260226000005	RemoveValidUntilFromSubscriptions	\N	2026-02-25 17:15:07	2026-02-25 17:15:07	f
\.


--
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.devices (id, device_uuid, custom_name, hardware_model, first_activation_date, user_id, created, modified, platform, os_version, app_version, instance_id, deleted_at) FROM stdin;
a75ea09f-56d8-469c-b592-f482113d4657	test-abc-123	test	iPhone14,2	2026-02-24 14:53:13.53684	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	2026-02-25 16:54:11	2026-02-25 16:54:12	\N	\N	\N	1e74793a-d755-469a-b081-b1d5a516b407	\N
d63c62ea-d280-4209-8f8b-c8bf92d24ef3	6775EAB8-2A4E-40B7-864C-49421AA08286	tdasdsadfsvsdfvsdfvsdfvsdfvsfdvsdfvsdfvsdfvsdfvsdfvsdfvsdfvdsfvsdfvsdfvsdfvsdfvsdfvsd	\N	2026-02-26 12:18:45.546318	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	2026-02-26 12:18:45.547073	2026-02-26 14:36:21.829866	\N	\N	\N	\N	\N
af9ebbf8-2907-4584-906e-7f320cc9ff25	A690320F-1101-408E-85FB-9F4AC9171903	\N	Apple iPhone18,1	2026-02-26 15:08:06.011164	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	2026-02-26 15:08:06.011244	2026-02-27 17:29:33.362076	ios	iOS 26.2	1.0.0+2	1e74793a-d755-469a-b081-b1d5a516b407	\N
\.


--
-- Data for Name: instances; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.instances (id, name, club_admin_id, is_active, created, modified, deleted_at) FROM stdin;
bfc6c923-3680-4967-8528-eb6d60bb09b7	com.ibarracc.ctz	\N	t	2026-02-25 06:35:46.87229	2026-02-25 06:35:46.872393	\N
1e74793a-d755-469a-b081-b1d5a516b407	com.ibarracc.triggertime	4eb8fdb2-0a78-49b3-85bc-dfd876d530f6	t	2026-02-25 04:37:05.27186	2026-03-02 09:54:22.034227	\N
\.


--
-- Data for Name: password_resets; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.password_resets (id, user_id, token, expires_at, used, created, modified) FROM stdin;
a5660873-ace0-4994-806d-4588561e194b	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	9dde238f36aa8f60db90fef2eecb20e03d31c015c3fcad38a196306457d47677	2026-02-26 06:08:27.086984	t	2026-02-25 06:08:27.146783	2026-02-25 06:09:19.948578
d2e750a5-484d-4509-9afe-29094fd33d71	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	6bd59a605bd69299ef2f91989f0e83d332a56a5ae779d3c81890f060cc726331	2026-02-26 15:58:47.879553	t	2026-02-25 15:58:47.905163	2026-02-25 15:59:09.877726
\.


--
-- Data for Name: subscription_devices; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.subscription_devices (id, subscription_id, device_id, created, modified) FROM stdin;
\.


--
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.subscriptions (id, user_id, stripe_subscription_id, plan, status, max_devices_allowed, created, modified, deleted_at, current_period_start, current_period_end, cancel_at_period_end) FROM stdin;
728b5404-b926-45ae-959c-81b38eddc322	149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	sub_1T4luS3rQyHr8czv0U3z10qb	pro	active	999	2026-02-25 17:30:07.134548	2026-02-25 17:38:28.253166	\N	2026-02-25 17:30:02	2026-03-25 17:30:02	t
\.


--
-- Data for Name: upgrade_tokens; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.upgrade_tokens (id, token_string, device_uuid, expires_at, is_used, created, modified, type) FROM stdin;
380e7e2d-5fe6-4da4-809b-56193a5617b9	4OY3SZ	string	2026-02-23 15:48:33.992393	f	2026-02-23 15:33:33.993728	2026-02-23 15:33:33.993866	upgrade
a5b6e364-967f-4af0-a4ae-6a77e0686218	bafb80a2-b4d0-4370-af32-eb105169726d	6775EAB8-2A4E-40B7-864C-49421AA08286	2026-02-26 12:33:36.342232	t	2026-02-26 12:18:36.344629	2026-02-26 12:18:45.555374	upgrade
7b1f4e78-4ced-40c3-a32d-82e73f6e5d86	7ae07da7-4bca-4c4a-8a86-887d7af0ffeb	test-abc-123	2026-02-26 13:40:08.930852	f	2026-02-26 13:25:09.140696	2026-02-26 13:25:09.142846	upgrade
47a448ec-41a2-4ad0-a229-880e06a779a3	8b77bd3f-37b8-45b1-b15f-8914c42fa6fd	A690320F-1101-408E-85FB-9F4AC9171903	2026-02-27 17:44:25.217545	t	2026-02-27 17:29:25.219033	2026-02-27 17:29:33.383772	upgrade
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.users (id, email, password_hash, role, stripe_customer_id, created_at, deleted_at, first_name, last_name) FROM stdin;
4eb8fdb2-0a78-49b3-85bc-dfd876d530f6	club@triggertime.es	$2y$12$gvaLb.YxE3ZMa3L0awq9RuR.Uv2lynDKutR2tStf.TKV4gtGfIrkK	club_admin	\N	2026-02-25 06:34:25.790192	\N	\N	\N
778cafa8-4230-4db7-9b77-75b3e09df765	alejandro@triggertime.es	$2y$12$IAQOC/VfA.kLdJXhBQ5hYOHWX4PMATC0brFEH8oyxg9v3F6dZC7Lu	admin	\N	2026-02-25 04:37:40	\N	Alejandro	Ibarra
149b44c0-1d8a-471a-a7cf-cd87d94a8fb9	ajibarra@gmail.com	$2y$12$BmG58cgSgWa8y9Vp0IIAO.fNsHXoH6A6uZyVR2pSLKgQiDGDX/yRC	user	cus_U2rcX0kMtq9a80	2026-02-25 04:19:59.158022	\N		
\.


--
-- Data for Name: versions; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.versions (id, version, disabled, created, modified, instance_id) FROM stdin;
1	1.0.0-b6	f	2026-02-25 11:23:21.232205	2026-02-26 14:59:52.588852	bfc6c923-3680-4967-8528-eb6d60bb09b7
3	1.0.0-b6	f	2026-02-26 15:00:06.545123	2026-02-26 15:04:38.979993	\N
\.


--
-- Name: activation_licenses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.activation_licenses_id_seq', 1, true);


--
-- Name: app_remote_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.app_remote_config_id_seq', 3, true);


--
-- Name: cake_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.cake_migrations_id_seq', 23, true);


--
-- Name: subscription_devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.subscription_devices_id_seq', 10, true);


--
-- Name: versions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.versions_id_seq', 3, true);


--
-- Name: activation_licenses activation_licenses_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.activation_licenses
    ADD CONSTRAINT activation_licenses_pkey PRIMARY KEY (id);


--
-- Name: app_remote_config app_remote_config_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.app_remote_config
    ADD CONSTRAINT app_remote_config_pkey PRIMARY KEY (id);


--
-- Name: cake_migrations cake_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.cake_migrations
    ADD CONSTRAINT cake_migrations_pkey PRIMARY KEY (id);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: instances instances_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.instances
    ADD CONSTRAINT instances_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);


--
-- Name: subscription_devices subscription_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.subscription_devices
    ADD CONSTRAINT subscription_devices_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: upgrade_tokens upgrade_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.upgrade_tokens
    ADD CONSTRAINT upgrade_tokens_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_stripe_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_stripe_customer_id_key UNIQUE (stripe_customer_id);


--
-- Name: versions versions_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.versions
    ADD CONSTRAINT versions_pkey PRIMARY KEY (id);


--
-- Name: activation_licenses_license_number; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX activation_licenses_license_number ON public.activation_licenses USING btree (license_number);


--
-- Name: devices_device_uuid; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX devices_device_uuid ON public.devices USING btree (device_uuid);


--
-- Name: idx_app_cfg_inst; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX idx_app_cfg_inst ON public.app_remote_config USING btree (instance_id, version_id);


--
-- Name: idx_app_ver_inst; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX idx_app_ver_inst ON public.versions USING btree (instance_id, version);


--
-- Name: idx_lic_inst; Type: INDEX; Schema: public; Owner: db
--

CREATE INDEX idx_lic_inst ON public.activation_licenses USING btree (instance_id);


--
-- Name: idx_sd_dev; Type: INDEX; Schema: public; Owner: db
--

CREATE INDEX idx_sd_dev ON public.subscription_devices USING btree (device_id);


--
-- Name: idx_sd_sub; Type: INDEX; Schema: public; Owner: db
--

CREATE INDEX idx_sd_sub ON public.subscription_devices USING btree (subscription_id);


--
-- Name: idx_sub_user; Type: INDEX; Schema: public; Owner: db
--

CREATE INDEX idx_sub_user ON public.subscriptions USING btree (user_id);


--
-- Name: idx_token_exp; Type: INDEX; Schema: public; Owner: db
--

CREATE INDEX idx_token_exp ON public.upgrade_tokens USING btree (token_string, expires_at);


--
-- Name: instances_name; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX instances_name ON public.instances USING btree (name);


--
-- Name: licenses_email_instance_id; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX licenses_email_instance_id ON public.activation_licenses USING btree (email, instance_id);


--
-- Name: password_resets_token; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX password_resets_token ON public.password_resets USING btree (token);


--
-- Name: subscription_devices_subscription_id_device_id; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX subscription_devices_subscription_id_device_id ON public.subscription_devices USING btree (subscription_id, device_id);


--
-- Name: subscriptions_stripe_subscription_id; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX subscriptions_stripe_subscription_id ON public.subscriptions USING btree (stripe_subscription_id);


--
-- Name: upgrade_tokens_token_string; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX upgrade_tokens_token_string ON public.upgrade_tokens USING btree (token_string);


--
-- Name: version_plugin_unique; Type: INDEX; Schema: public; Owner: db
--

CREATE UNIQUE INDEX version_plugin_unique ON public.cake_migrations USING btree (version, plugin);


--
-- Name: activation_licenses activation_licenses_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.activation_licenses
    ADD CONSTRAINT activation_licenses_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE SET NULL;


--
-- Name: activation_licenses activation_licenses_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.activation_licenses
    ADD CONSTRAINT activation_licenses_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: activation_licenses activation_licenses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.activation_licenses
    ADD CONSTRAINT activation_licenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: app_remote_config app_remote_config_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.app_remote_config
    ADD CONSTRAINT app_remote_config_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: app_remote_config app_remote_config_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.app_remote_config
    ADD CONSTRAINT app_remote_config_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.versions(id) ON DELETE SET NULL;


--
-- Name: devices devices_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: devices devices_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: instances instances_club_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.instances
    ADD CONSTRAINT instances_club_admin_id_fkey FOREIGN KEY (club_admin_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: subscription_devices subscription_devices_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.subscription_devices
    ADD CONSTRAINT subscription_devices_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE;


--
-- Name: subscription_devices subscription_devices_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.subscription_devices
    ADD CONSTRAINT subscription_devices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE CASCADE;


--
-- Name: subscriptions subscriptions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: versions versions_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.versions
    ADD CONSTRAINT versions_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict BhoksptKVW2II8RdxRaaLubchnkH5jvehE9RxzOI1jkPnRL10bM9fxGS1dePhWd

