<?php

declare(strict_types=1);

use Migrations\BaseMigration;

class SeedCalibersAndBrands extends BaseMigration
{
    /**
     * Seed calibers and brands reference data.
     *
     * @return void
     */
    public function up(): void
    {
        $now = date('Y-m-d H:i:s');

        // ── Calibers ──
        $caliberData = $this->getCaliberData();
        $calibers = $this->table('calibers');
        $seen = [];
        $rows = [];

        foreach ($caliberData as $category => $standards) {
            foreach ($standards as $standard => $names) {
                $sortOrder = 0;
                foreach ($names as $name) {
                    $key = $name . '|' . $category . '|' . $standard;
                    if (isset($seen[$key])) {
                        continue;
                    }
                    $seen[$key] = true;
                    $rows[] = [
                        'name' => $name,
                        'weapon_category' => $category,
                        'standard' => $standard,
                        'is_active' => true,
                        'sort_order' => $sortOrder++,
                        'created' => $now,
                        'modified' => $now,
                    ];
                }
            }
        }

        // Insert in batches to avoid memory issues
        foreach (array_chunk($rows, 100) as $batch) {
            $calibers->insert($batch)->saveData();
        }

        // ── Brands ──
        $brands = $this->table('brands');
        $brandRows = [];
        $sortOrder = 0;

        foreach ($this->getBrandData() as $brand) {
            $brandRows[] = [
                'name' => $brand['name'],
                'country' => $brand['country'],
                'is_active' => true,
                'sort_order' => $sortOrder++,
                'created' => $now,
                'modified' => $now,
            ];
        }

        $brands->insert($brandRows)->saveData();
    }

    /**
     * @return void
     */
    public function down(): void
    {
        $this->execute('DELETE FROM calibers');
        $this->execute('DELETE FROM brands');
    }

    /**
     * Returns caliber data organized by category and standard.
     *
     * @return array<string, array<string, array<string>>>
     */
    private function getCaliberData(): array
    {
        return [
            'pistol' => [
                'saami' => [
                    '10mm Automatic',
                    '221 Remington Fireball',
                    '25 Automatic',
                    '25 North American Arms',
                    '30 Luger (7.65mm)',
                    '32 Automatic',
                    '32 H&R Magnum',
                    '32 North American Arms',
                    '32 Short Colt',
                    '32 Smith & Wesson Long Wadcutter',
                    '32 Smith & Wesson Long',
                    '32 Smith & Wesson',
                    '327 Federal Magnum',
                    '356 TSW',
                    '357 Magnum',
                    '357 Sig',
                    '38 Automatic',
                    '38 Smith & Wesson',
                    '38 Special +P',
                    '38 Special Match',
                    '38 Special',
                    '38 Super Automatic +P',
                    '380 Automatic',
                    '40 Smith & Wesson',
                    '400 Cor-Bon',
                    '41 Remington Magnum',
                    '44 Remington Magnum',
                    '44 S&W Special',
                    '45 Auto Rim',
                    '45 Automatic +P',
                    '45 Automatic Match',
                    '45 Automatic',
                    '45 Colt',
                    '45 Glock Automatic Pistol',
                    '45 Winchester Magnum',
                    '454 Casull',
                    '460 S&W Magnum',
                    '475 Linebaugh',
                    '480 Ruger',
                    '50 Action Express',
                    '500 S&W Magnum',
                    '500 Special',
                    '9mm Luger +P',
                    '9mm Luger',
                    '9x18 Makarov',
                    '9x23 Winchester',
                ],
                'cip' => [
                    '5.45 x 18',
                    '5.75 Velodog',
                    '6.35 Browning',
                    '7 x 49 Guido J. Wasser',
                    '7 Penna',
                    '7mm Penna L',
                    '7.5 FK',
                    '7.5 Ordonnance Suisse',
                    '7.62 x 25 Tokarev',
                    '7.62 Nagant',
                    '7.63 Mauser',
                    '7.65 Browning',
                    '7.65 Long',
                    '7.65 Parabellum',
                    '8mm Gasser',
                    '8mm Lebel',
                    '8mm Steyr',
                    '9 x 18',
                    '9 x 20 VGW',
                    '9 x 21',
                    '9 x 22 Major',
                    '9 x 25 Super Automatic G',
                    '9mm Makarov',
                    '9mm Browning court',
                    '9mm Browning long',
                    '9mm Fast Accurate Reliable',
                    '9mm FX & CQT',
                    '9mm Luger',
                    '9mm Mauser',
                    '9mm Steyr',
                    '10 x 22 T',
                    '10mm Automatic',
                    '10mm Fast Accurate Reliable',
                    '10.4 Ordinanza Italiana',
                    '11mm 73',
                    '22 PICRA',
                    '22 Remington Jet Magnum',
                    '221 Remington Fireball',
                    '260 PICRA',
                    '30 PICRA',
                    '30-357 Armi e Tiro',
                    '32 Harrington & Richardson Magnum',
                    '32 Long Colt',
                    '32 Short Colt',
                    '32 Smith & Wesson',
                    '32 Smith & Wesson Long',
                    '32 Smith & Wesson Long Wad Cutter',
                    '320 Long',
                    '320 Short',
                    '357 Automatic Magnum',
                    '357 Magnum',
                    '357 Magnum (carb)',
                    '357 Maximum',
                    '357 SIG',
                    '38 Long Colt',
                    '38 Short Colt',
                    '38 Smith & Wesson. Colt New Police',
                    '38 Special',
                    '38 Special (carb)',
                    '38 Special Army Marksmanship Unit',
                    '38 Special Wad Cutter',
                    '38 Super Automatic',
                    '38/357 FX',
                    '38-45 Automatic Colt Pistol',
                    '380 Long',
                    '380 Short',
                    '40 Smith & Wesson',
                    '41 Action Express',
                    '41 Long Colt',
                    '41 Remington Magnum',
                    '44 Colt',
                    '44 Remington Magnum',
                    '44 Remington Magnum (carb)',
                    '44 Smith & Wesson Russian',
                    '44 Smith & Wesson Special',
                    '44 Smith & Wesson Special (carb)',
                    '45 Automatic',
                    '45 Automatic Rim',
                    '45 Colt',
                    '45 Colt (carb)',
                    '45 Glock Auto Pistol',
                    '45 HP',
                    '45 Smith & Wesson Schofield',
                    '45 Smith & Wesson Schofield (carb)',
                    '45 Winchester Magnum',
                    '450 SCH',
                    '450 Short',
                    '454 Casull',
                    '455 MK II',
                    '460 Smith & Wesson Magnum',
                    '475 Linebaugh',
                    '480 Ruger',
                    '50 Action Express',
                    '500 Smith & Wesson Magnum',
                ],
            ],
            'rifle' => [
                'saami' => [
                    '17 Hornet',
                    '17 Remington Fireball',
                    '17 Remington',
                    '204 Ruger',
                    '218 Bee',
                    '22 Hornet',
                    '22-250 Remington',
                    '220 Swift',
                    '221 Remington Fireball',
                    '222 Remington Magnum',
                    '222 Remington',
                    '223 Remington',
                    '223 Winchester Super Short Magnum',
                    '225 Winchester',
                    '243 Winchester Super Short Magnum',
                    '243 Winchester',
                    '25 Winchester Super Short Magnum',
                    '25-06 Remington',
                    '25-20 Winchester',
                    '25-35 Winchester',
                    '250 Savage',
                    '257 Roberts +P',
                    '257 Roberts',
                    '257 Weatherby Magnum',
                    '26 Nosler',
                    '260 Remington',
                    '264 Winchester Magnum',
                    '27 Nosler',
                    '270 Weatherby Magnum',
                    '270 Winchester Short Magnum',
                    '270 Winchester',
                    '28 Nosler',
                    '280 Ackley Improved',
                    '280 Remington',
                    '284 Winchester',
                    '30 Carbine',
                    '30 Nosler',
                    '30 Remington AR',
                    '30 Thompson Center',
                    '30-06 Springfield',
                    '30-30 Winchester',
                    '30-40 Krag',
                    '300 AAC Blackout',
                    '300 Holland & Holland Magnum',
                    '300 Remington Short Action Ultra Magnum',
                    '300 Remington Ultra Magnum',
                    '300 Ruger Compact Magnum',
                    '300 Savage',
                    '300 Weatherby Magnum',
                    '300 Winchester Magnum',
                    '300 Winchester Short Magnum',
                    '303 British',
                    '307 Winchester',
                    '308 Marlin Express',
                    '308 Winchester',
                    '32 Winchester Special',
                    '32-20 Winchester',
                    '325 Winchester Short Magnum',
                    '33 Nosler',
                    '338 Federal',
                    '338 Lapua Magnum',
                    '338 Marlin Express',
                    '338 Remington Ultra Magnum',
                    '338 Ruger Compact Magnum',
                    '338 Winchester Magnum',
                    '340 Weatherby Magnum',
                    '348 Winchester',
                    '35 Nosler',
                    '35 Remington',
                    '35 Whelen',
                    '350 Remington Magnum',
                    '356 Winchester',
                    '358 Winchester',
                    '36 Nosler',
                    '370 Sako Magnum',
                    '375 Holland & Holland Magnum',
                    '375 Remington Ultra Magnum',
                    '375 Ruger',
                    '375 Winchester',
                    '376 Steyr',
                    '38-40 Winchester',
                    '38-55 Winchester',
                    '405 Winchester',
                    '416 Remington Magnum',
                    '416 Rigby',
                    '416 Ruger',
                    '416 Weatherby Magnum',
                    '44 Remington Magnum',
                    '44-40 Winchester',
                    '444 Marlin',
                    '45-70 Government',
                    '450 Bushmaster',
                    '450 Marlin',
                    '457 Wild West Guns',
                    '458 Lott',
                    '458 Winchester Magnum',
                    '470 Nitro Express',
                    '475 Turnbull',
                    '500 Nitro Express 3"',
                    '6 x 45mm',
                    '6.5 Creedmoor',
                    '6.5 Grendel',
                    '6.5 x 55 Swedish',
                    '6.8mm Remington SPC',
                    '6mm Remington',
                    '7 x 64 Brenneke',
                    '7-30 Waters',
                    '7.62 x 39',
                    '7mm Mauser (7x57)',
                    '7mm Remington Magnum',
                    '7mm Remington Short Action Ultra Magnum',
                    '7mm Remington Ultra Magnum',
                    '7mm Shooting Times Westerner',
                    '7mm Weatherby Magnum',
                    '7mm Winchester Short Magnum',
                    '7mm-08 Remington',
                    '8mm Mauser (8 x 57)',
                    '8mm Remington Magnum',
                    '9.3 x 62',
                ],
                'cip' => [
                    '215',
                    '4.6 x 30',
                    '5mm / 35 SMc',
                    '5.45 x 39',
                    '5.6 x 39',
                    '5.6 x 50 Magnum',
                    '5.6 x 57',
                    '5.6 x 61 Super Express Vom Hofe',
                    '5.7 x 28',
                    '6 x 47 ATZL',
                    '6 x 47 SM',
                    '6 x 51 ATZL',
                    '6 x 62 Freres',
                    '6mm Bench Rest Fare',
                    '6mm Bench Rest Norma',
                    '6mm Bench Rest Remington',
                    '6mm D.B.G.',
                    '6mm Palmisano & Pindel Cartridge',
                    '6mm Palmisano & Pindel Cartridge ITA',
                    '6mm Palmisano & Pindel Cartridge-USA',
                    '6mm Remington (244 Remington)',
                    '6 XC',
                    '6.3 x 57 Fare',
                    '6.5 - 284 Norma',
                    '6.5 x 39',
                    '6.5 x 47 Lapua',
                    '6.5 x 52 Carcano',
                    '6.5 x 54 Mauser',
                    '6.5 x 54 Mannlicher-Schonauer',
                    '6.5 x 55 SE',
                    '6.5 x 55 T.R.I.',
                    '6.5 x 57',
                    '6.5 x 58 Mauser',
                    '6.5 x 63 Messner Magnum',
                    '6.5 x 64',
                    '6.5 x 64 Brenneke',
                    '6.5 x 65 RWS',
                    '6.5 x 68',
                    '6.5 Creedmoor',
                    '6.5 Grendel',
                    '6.5mm D.B.G.',
                    '6.5mm Lahoz',
                    '6.8mm Remington Special Purpose Cartridge',
                    '7 x 33 Sako',
                    '7 x 44 Penna',
                    '7 x 57',
                    '7 x 64',
                    '7-47 Giani Special',
                    '7mm - 08 Remington',
                    '7mm Blaser Magnum',
                    '7mm Bench Rest Remington',
                    '7mm Express Remington',
                    '7mm KM',
                    '7mm Remington Short Action Ultra Magnum',
                    '7mm Remington Ultra Magnum',
                    '7mm Super Express Vom Hofe',
                    '7mm Winchester Short Magnum',
                    '7.21 Firebird',
                    '7.5 x 54 MAS',
                    '7.5 x 55 Suisse',
                    '7.62 x 39',
                    '7.62 x 45',
                    '7.62 UKM',
                    '7.65 x 53 Argentine',
                    '7.82 Warbird',
                    '7.92 x 24 VBR',
                    '7.92 x 33 kurz',
                    '8 x 51 (Mauser K)',
                    '8 x 56 Mannlicher-Schonauer',
                    '8 x 57 I',
                    '8 x 57 IS',
                    '8 x 57 PCC',
                    '8 x 60',
                    '8 x 60 S',
                    '8 x 64',
                    '8 x 64 S',
                    '8 x 68 S',
                    '8 x 75 S',
                    '8.5 x 63',
                    '8.5 x 68 Fanzoj',
                    '8.5mm Messner Magnum',
                    '9 x 56 Mannlicher-Schonauer',
                    '9 x 57',
                    '9.3 x 57',
                    '9.3 x 62',
                    '9.3 x 64 Brenneke',
                    '9.3 x 66 Sako',
                    '9.3 Roedale Short Magnum',
                    '9.5 x 57 Mannlicher-Schonauer',
                    '9.5 x 66 Super Express Vom Hofe',
                    '10.3 CSP',
                    '10.75 x 68',
                    '12.7 x 70 (500 Schuler)',
                    '12.7 x 108',
                    '17 Libra',
                    '17 Remington',
                    '17 Remington Fireball',
                    '204 Ruger',
                    '22 Palmisano & Pindel Cartridge-USA',
                    '22-250 Remington',
                    '220 Swift',
                    '222 Remington',
                    '222 Remington Magnum',
                    '223 Remington',
                    '223 Winchester Super Short Magnum',
                    '243 Winchester',
                    '243 Winchester Super Short Magnum',
                    '25 Remington',
                    '25 Winchester SSM',
                    '25-06 Remington',
                    '250 Savage',
                    '255 Giani Special',
                    '256 Magnum Gibbs',
                    '257 Roberts',
                    '260 Remington',
                    '264 Leroy Nitro Express',
                    '270 Winchester',
                    '270 Winchester Short Magnum',
                    '275 H.V. Rigby',
                    '277 Giani Special',
                    '280 Remington',
                    '280 Rimless Nitro Express Ross',
                    '284 Tony',
                    '284 Winchester',
                    '30 BR',
                    '30 Carbine',
                    '30 Court',
                    '30 Remington',
                    '30 TC',
                    '30-06 Ackley Improved',
                    '30-06 Court Cartry',
                    '30-06 Springfield',
                    '30-284 NOLASCO',
                    '30-284 Winchester',
                    '30-338 Prechtl Magnum',
                    '30-47 Giani Special',
                    '300 AAC Blackout',
                    '300 Blacktornado',
                    '300 Blaser Magnum',
                    '300 CR',
                    '300 Lapua Magnum',
                    '300 Norma Magnum',
                    '300 Pegasus',
                    '300 RCM',
                    '300 Remington Short Action Ultra Magnum',
                    '300 Remington Ultra Magnum',
                    '300 Savage',
                    '300 Winchester Short Magnum',
                    '308 EH',
                    '308 Match',
                    '308 Winchester',
                    '318 Rimless Nitro Express',
                    '32 Remington',
                    '325 Winchester Short Magnum',
                    '333 Rimless Nitro Express',
                    '338 Blaser Magnum',
                    '338 Federal',
                    '338 Lapua Magnum',
                    '338 Norma Magnum',
                    '338 RCM',
                    '338 Remington Ultra Magnum',
                    '338 Winchester Short Magnum',
                    '35 Remington',
                    '35 Whelen',
                    '350 Magnum Rigby',
                    '358 Winchester',
                    '375 Blaser Magnum',
                    '375 Chey Tac',
                    '375 Holderlin',
                    '375 Remington Ultra Magnum',
                    '375 Ruger',
                    '376 Steyr',
                    '404 Rimless Nitro Express',
                    '408 Chey Tac',
                    '416 A-TEC',
                    '416 Barrett',
                    '416 Rigby',
                    '416 Ruger',
                    '416 Taylor',
                    '45 Blaser',
                    '450 Bushmaster',
                    '450 Rigby',
                    '460 Steyr',
                    '50 Browning',
                    '500 Jeffery',
                    '505 Magnum Gibbs',
                    '510 DTC',
                    '5.6 x 35 R',
                    '5.6 x 50 R Magnum',
                    '5.6 x 52 R',
                    '5.6 x 57 R',
                    '5.6 x 61 R Super Express Vom Hofe',
                    '5.6 x 70 R',
                    '6 x 50 R Scheiring',
                    '6 x 52 R BB2',
                    '6 x 52 R Bretschneider',
                    '6 x 62 R Freres',
                    '6 x 70 R',
                    '6.5 x 50 R',
                    '6.5 x 51 R (Arisaka)',
                    '6.5 x 52 R',
                    '6.5 x 52 R Keller & Simmann',
                    '6.5 x 57 R',
                    '6.5 x 58 R',
                    '6.5 x 65 R RWS',
                    '6.5 x 68 R',
                    '6.5 x 70 R',
                    '7-30 Waters',
                    '7 x 50 R',
                    '7 x 57 R',
                    '7mm Magnum Flanged Holland & Holland',
                    '7 x 65 R',
                    '7 x 67 R Luyven',
                    '7 x 72 R',
                    '7 x 75 R Super Express Vom Hofe',
                    '7.62 x 53 R',
                    '7.62 x 54 R',
                    '8 x 50 R',
                    '8 x 51 R Lebel',
                    '8 x 56 R M30S',
                    '8 x 56 R M89 Portuguese Kropatschek',
                    '8 x 57 R 360',
                    '8 x 57 IR',
                    '8 x 57 IRS',
                    '8 x 58 R',
                    '8 x 60 R',
                    '8 x 60 RS',
                    '8 x 65 R',
                    '8 x 65 RS',
                    '8 x 72 R',
                    '8 x 75 RS',
                    '8mm - 348 Winchester',
                    '8.15 x 46 R',
                    '8.2 x 53 R',
                    '8.5 x 63 R',
                    '8.5 x 75 R Scheiring',
                    '9 x 53 R',
                    '9 x 57 R',
                    '9.3 x 53 R Finnish',
                    '9.3 x 72 R',
                    '9.3 x 74 R',
                    '10.3 x 60 R',
                    '11.15 x 60 R',
                    '17 Hornet',
                    '218 Bee',
                    '219 Zipper',
                    '22 Hornet',
                    '22 Savage',
                    '222 R Stief',
                    '225 Winchester',
                    '240 Flanged Nitro Express',
                    '25-20 Winchester',
                    '25-35 Winchester',
                    '256 Winchester Magnum',
                    '280 Flanged Nitro Express',
                    '297/230 Morris Long',
                    '297/230 Morris sh',
                    '30 R Blaser',
                    '30 Flanged Nitro Express Purdey',
                    '30 Super Flanged Holland & Holland',
                    '30-06 R Stief',
                    '30-30 Winchester',
                    '30-40 Krag',
                    '300/295 Rook Rifle',
                    '300 Sherwood',
                    '303 British',
                    '303 Savage',
                    '303 Sporting',
                    '307 Winchester',
                    '308 Marlin Express',
                    '310 Cadet Rifle',
                    '32 Winchester Self-loading',
                    '32 Winchester Special',
                    '32-20 Winchester',
                    '32-40 Winchester',
                    '33 Winchester',
                    '338 Marlin Express',
                    '348 Winchester',
                    '35 Winchester',
                    '35 Winchester Self-loading',
                    '350 No. 2 Rigby',
                    '351 Winchester Self-loading',
                    '356 Winchester',
                    '360 Nitro Express 21/4',
                    '369 Nitro Express Purdey',
                    '375 Flanged Nitro Express 21/2',
                    '375 Flanged Magnum Nitro Express',
                    '375 R Holderlin',
                    '375 R Verney-Carron',
                    '375 Winchester',
                    '38-40 Winchester',
                    '38-55 Winchester',
                    '380 Long Rifle',
                    '40-60 Winchester',
                    '40-65 Winchester',
                    '40-82 Winchester',
                    '400 Purdey 3"',
                    '400/350 Nitro Express',
                    '401 Winchester Self-loading',
                    '405 Winchester',
                    '408 Winchester',
                    '44-40 Winchester',
                    '444 Marlin',
                    '45-60 Winchester',
                    '45-70 Elko Magnum',
                    '45-70 Government',
                    '45-75 Winchester',
                    '45-90 WM',
                    '45-110 Sharps 2" 7/8',
                    '45-120 Sharps 3" 1/4',
                    '450 Nitro Express 3" 1/4',
                    '450 No 2 Nitro Express 3" 1/2 Eley',
                    '450/400 Nitro Express 3',
                    '450/400 Magnum Nitro Express 31/4',
                    '470 Nitro Express',
                    '475 No 2 Nitro Express 31/2',
                    '475 No 2 Nitro Express 3" 1/2 Jeffery',
                    '50-70 Government',
                    '50-90 Sharps 2" 1/2',
                    '50-95 Winchester',
                    '500 Nitro Express 3"',
                    '500/416 Nitro Express 3" 1/4',
                    '500/465 Nitro Express',
                    '56/50 Spencer',
                    '577/450 Sld. Martini-Henry',
                    '577 Nitro Express 3"',
                    '577 Sld. Snider',
                    '600 Nitro Express',
                    '700 Holland & Holland Nitro Express',
                    '4 Bore Rifle',
                    '6.5mm Remington Magnum',
                    '7 x 61 Super',
                    '7mm Remington Magnum',
                    '7mm Rose',
                    '7mm Shooting Times Westerner',
                    '7mm Weatherby Magnum',
                    '8mm Remington Magnum',
                    '11.5 x 51',
                    '224 Weatherby Magnum',
                    '240 Belted Rimless Nitro Express',
                    '240 Weatherby Magnum',
                    '244 Holland & Holland Magnum',
                    '257 Weatherby Magnum',
                    '264 Winchester Magnum',
                    '270 Weatherby Magnum',
                    '275 Belted Nitro Express',
                    '30 Super Belted Rimless Holland & Holland',
                    '30-378 Weatherby Magnum',
                    '300 Holland & Holland Magnum',
                    '300 Weatherby Magnum',
                    '300 Winchester Magnum',
                    '308 Norma Magnum',
                    '338 Winchester Magnum',
                    '338-378 Weatherby Mag',
                    '340 Weatherby Magnum',
                    '350 Remington Magnum',
                    '358 Norma Magnum',
                    '375 Holland & Holland Magnum',
                    '375 Weatherby Magnum',
                    '378 Weatherby Magnum',
                    '400 Holland & Holland Belted Magnum',
                    '416 Remington Magnum',
                    '416 Taylor Magnum',
                    '416 Weatherby Magnum',
                    '450 Marlin',
                    '458 Lott',
                    '458 Winchester Magnum',
                    '460 Weatherby Magnum',
                    '465 Holland & Holland Belted Magnum',
                ],
            ],
            'rimfire' => [
                'saami' => [
                    '17 Hornady Magnum Rimfire',
                    '17 Mach 2',
                    '17 Winchester Super Magnum',
                    '22 Long Rifle - Match',
                    '22 Long Rifle - Shot',
                    '22 Long Rifle - Sporting',
                    '22 Long',
                    '22 Short',
                    '22 Winchester Magnum',
                    '22 Winchester Rimfire',
                ],
                'cip' => [
                    '4mm Randz. court',
                    '4mm Randz. long',
                    '5mm Remington Magnum',
                    '5.6mm (22) Flobert a balle',
                    '5.6mm Flobert a plombs SC',
                    '5.6mm Flobert a plombs DC',
                    '6mm Flobert a balle',
                    '6mm Flobert a balle DC',
                    '6mm ME Flobert court',
                    '9mm Flobert a balle',
                    '9mm Flobert a plombs Carton',
                    '9mm Flobert a plombs Metal',
                    '22 Bulleted Breech Cap',
                    '22 Conical Ball Cap',
                    '22 Long',
                    '22 Extra Long',
                    '22 Extra L.R.',
                    '22 Long Shot',
                    '22 Long Rifle Shot Claybirding',
                    '22 Remington Automatic',
                    '22 Winchester Automatic',
                    '22 Winchester Magnum Rimfire et 22 Remington Special',
                    '17 Hornady Magnum Rimfire',
                    '17 Mach 2',
                    '17 Winchester Super Magnum',
                    '22 Long Rifle',
                    '22 Short',
                    '22 Winchester Magnum Rimfire',
                ],
            ],
            'shotshell' => [
                'saami' => [
                    '10 Gauge 3 1/2" Smooth bore',
                    '12 Gauge 2 3/4" Rifled',
                    '12 Gauge 2 3/4" Smooth bore',
                    '12 Gauge 3" Rifled',
                    '12 Gauge 3" Smooth bore',
                    '12 Gauge 3 1/2" Smooth bore',
                    '16 Gauge 2 3/4" Smooth bore',
                    '20 Gauge 2 3/4" Rifled',
                    '20 Gauge 2 3/4" Smooth bore',
                    '20 Gauge 3" Rifled',
                    '20 Gauge 3" Smooth bore',
                    '28 Gauge 2 3/4" Smooth bore',
                    '410 Bore 2 1/2" Smooth bore',
                    '410 Bore 3" Smooth bore',
                ],
                'cip' => [
                    '4/82',
                    '4/101',
                    '8/82',
                    '8/100',
                    '10/76',
                    '10/82',
                    '10/89',
                    '12/35 T',
                    '12/50 SAPL',
                    '12/60',
                    '12/65',
                    '12/67',
                    '12/70',
                    '12/73',
                    '12/76',
                    '12/89',
                    '14/65',
                    '14/67',
                    '14/70',
                    '16/65',
                    '16/67',
                    '16/70',
                    '16/76',
                    '20/65',
                    '20/67',
                    '20/70',
                    '20/76',
                    '20/89',
                    '24/63.50',
                    '24/65',
                    '24/70',
                    '28/58.50',
                    '28/63.50',
                    '28/65',
                    '28/70',
                    '28/76',
                    '32/50.70',
                    '32/60',
                    '32/63.5',
                    '32/65',
                    '32/70',
                    '32/65 RUS',
                    '32/70 RUS',
                    '410/50.70',
                    '410/63.50',
                    '410/65',
                    '410/70',
                    '410/73',
                    '410/76',
                    '6 mm Centrale FALCO',
                    '8 mm C.F.',
                    '8/47.5 mm C.F.',
                    '9 mm C.F.',
                    '9 mm C.F. Mori',
                ],
            ],
        ];
    }

    /**
     * Returns brand data with country information.
     *
     * @return array<array{name: string, country: string|null}>
     */
    private function getBrandData(): array
    {
        return [
            ['name' => 'Federal', 'country' => 'USA'],
            ['name' => 'Hornady', 'country' => 'USA'],
            ['name' => 'CCI', 'country' => 'USA'],
            ['name' => 'Remington', 'country' => 'USA'],
            ['name' => 'Winchester', 'country' => 'USA'],
            ['name' => 'Sellier & Bellot', 'country' => 'Czech Republic'],
            ['name' => 'Fiocchi', 'country' => 'Italy'],
            ['name' => 'PMC', 'country' => 'South Korea'],
            ['name' => 'Magtech', 'country' => 'Brazil'],
            ['name' => 'Aguila', 'country' => 'Mexico'],
            ['name' => 'Norma', 'country' => 'Sweden'],
            ['name' => 'Lapua', 'country' => 'Finland'],
            ['name' => 'Berger', 'country' => 'USA'],
            ['name' => 'Sierra', 'country' => 'USA'],
            ['name' => 'Nosler', 'country' => 'USA'],
            ['name' => 'Barnes', 'country' => 'USA'],
            ['name' => 'Speer', 'country' => 'USA'],
            ['name' => 'TulAmmo', 'country' => 'Russia'],
            ['name' => 'Wolf', 'country' => 'Russia'],
            ['name' => 'PPU (Prvi Partizan)', 'country' => 'Bosnia'],
            ['name' => 'Blazer', 'country' => 'USA'],
            ['name' => 'American Eagle', 'country' => 'USA'],
            ['name' => 'Eley', 'country' => 'Germany'],
            ['name' => 'RWS', 'country' => 'Germany'],
            ['name' => 'GECO', 'country' => 'Germany'],
            ['name' => 'Rottweil', 'country' => 'Germany'],
            ['name' => 'SK', 'country' => 'Germany'],
            ['name' => 'Frontier', 'country' => 'USA'],
            ['name' => 'Sig Sauer', 'country' => 'USA'],
            ['name' => 'Browning', 'country' => 'USA'],
            ['name' => 'Underwood', 'country' => 'USA'],
            ['name' => 'Black Hills', 'country' => 'USA'],
            ['name' => 'CorBon', 'country' => 'USA'],
            ['name' => 'Buffalo Bore', 'country' => 'USA'],
            ['name' => 'HSM', 'country' => 'USA'],
            ['name' => 'Weatherby', 'country' => 'USA'],
            ['name' => 'Sako', 'country' => 'Finland'],
            ['name' => 'Hirtenberger', 'country' => 'Germany'],
            ['name' => 'CBC', 'country' => 'Brazil'],
            ['name' => 'Armscor', 'country' => 'Philippines'],
            ['name' => 'IMI', 'country' => 'Israel'],
            ['name' => 'MEN', 'country' => 'Germany'],
            ['name' => 'GFL', 'country' => 'Italy'],
            ['name' => 'Dinamit Nobel', 'country' => 'Germany'],
            ['name' => 'Samson', 'country' => 'Israel'],
            ['name' => 'Igman', 'country' => 'Bosnia'],
            ['name' => 'BPS', 'country' => null],
            ['name' => 'Barnaul', 'country' => 'Russia'],
            ['name' => 'Red Army Standard', 'country' => 'Russia'],
            ['name' => 'Tula', 'country' => 'Russia'],
        ];
    }
}
