<?php

declare(strict_types=1);

use Migrations\BaseMigration;

class SeedDefaultAdmin extends BaseMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * https://book.cakephp.org/migrations/5/en/migrations.html#the-change-method
     *
     * @return void
     */
    public function up(): void
    {
        $users = $this->table('users');
        // Simple hash of 'password' (bcrypt). Note: The actual hashing function is governed by DefaultPasswordHasher in CakePHP.
        // Or we can just insert the raw hash for 'password' which is generated by CakePHP usually.
        // Let's use a known bcrypt hash for "password": $2y$10$72vI/zC71e8D7DrmXOTN6em/6W8k7cOoI6n3u2T4C2Tpw/s4kO53O

        $users->insert([
            [
                'id' => \Cake\Utility\Text::uuid(),
                'email' => 'alejandro@triggertime.es',
                'password_hash' => password_hash('password', PASSWORD_DEFAULT),
                'role' => 'admin',
                'created_at' => date('Y-m-d H:i:s')
            ]
        ])->saveData();
    }

    public function down(): void
    {
        $this->execute("DELETE FROM users WHERE email = 'alejandro@triggertime.es'");
    }
}
