---
- name: Deploy application
  hosts: all
  become: true
  pre_tasks:
    - name: Load vault secrets
      ansible.builtin.include_vars:
        file: "vault/{{ env_name }}.yml"
  roles:
    - deploy
    - app-crons
