---
- name: Harden server
  hosts: all
  become: true
  pre_tasks:
    - name: Load vault secrets
      ansible.builtin.include_vars:
        file: "vault/{{ env_name }}.yml"
  roles:
    - ssh
    - firewall
    - unattended-upgrades
    - certbot
    - nginx
    - postgres
    - backups
    - monitoring
    - cloudflare
